#!/bin/bash
#xrandr --output eDP-1 --auto --rotate normal --primary
#xrandr --output HDMI-2 --auto --rotate normal --above eDP-1 #--mode 2560x1600
xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-1-1 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-1-2 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-1-3 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-2-3 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-2-2 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-3 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-2 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-3-2 --auto --rotate normal --above eDP-1-1
#xrandr --output eDP-1-1 --auto --rotate normal --primary --output DP-1-3-2 --auto --rotate normal --above eDP-1-1 --output DP-1-3-3 --auto --rotate normal --right-of DP-1-3-2
